import {GettablePropName} from '@api/transformers';

export const demoData: Readonly<Partial<Record<GettablePropName, string>>> = {
  'lora/mode': 'RECEIVER',
  'lora/channel': '2',
  'lora/module': 'DRF1268DS',
  'lora/listenonly': '0',
  'lora/drf1268dscompatmode': '0',
  'lora/lorarange': 'L',
  'sportident/usb/onewayreceive': '0',
  'sportident/usb/force4800baudrate': '0',
  'sirap/enabled': '0',
  'sirap/ip': '',
  'sirap/ipport': '10000',
  'sportident/rs232/mode': 'RECEIVE',
  'sportident/rs232/onewayreceive': '0',
  'sportident/rs232/force4800baudrate': '0',
  'srr/enabled': '0',
  'srr/mode': 'RECEIVE',
  'srr/redchannel': '1',
  'srr/bluechannel': '1',
  'srr/redchannellistenonly': '0',
  'srr/bluechannellistenonly': '0',
  'power/charging': '1',
  'power/battery': '35',
  'device/name': 'Demo Device',
  'bluetooth/scan': JSON.stringify([
    {
      'py/object': 'init.MicroMock',
      BTAddress: 'B8:BC:5B:90:A3:A5',
      Name: '[TV] Samsung Q60 Series (55)',
      Found: 'False',
      Status: 'NotConnected',
    },
  ]),
  'network/listwifi':
    'LasePrivate\nno\n72\nDIRECT-2c-HP M15 LaserJet\nno\n60\nTP-Link_F2EB\nno\n55\nWiRoc\nyes\n52\nGhostbusters\nno\n37',
  'hashw/srr': '1',
  'hashw/rtc': '1',
  'hashw/rfcomm': '1',
  services: JSON.stringify({
    services: [
      {
        Name: 'WiRocPython',
        Status: 'active',
      },
      {
        Name: 'WiRocPythonWS',
        Status: 'active',
      },
      {
        Name: 'WiRocWatchDog',
        Status: 'active',
      },
    ],
  }),
  status: JSON.stringify({
    inputAdapters: [
      {
        TypeName: 'STATUS',
        InstanceName: 'status1',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'reclora1',
      },
      {
        TypeName: 'SI',
        InstanceName: 'sibtsp1',
      },
      {
        TypeName: 'SITEST',
        InstanceName: 'test1',
      },
      {
        TypeName: 'REPEATER',
        InstanceName: 'rcvRepeater1',
      },
    ],
    subscriberAdapters: [
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'SIMessage',
        Enabled: false,
        MessageInName: 'SI',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'SRRMessage',
        Enabled: false,
        MessageInName: 'SRR',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'Test',
        Enabled: false,
        MessageInName: 'SITEST',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'Status',
        Enabled: false,
        MessageInName: 'STATUS',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Status',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'SIMessage',
        Enabled: false,
        MessageInName: 'REPEATER',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Ack',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'SIMessageDouble',
        Enabled: true,
        MessageInName: 'REPEATER',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Ack',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'SIMessage',
        Enabled: false,
        MessageInName: 'REPEATER',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'SIMessageDouble',
        Enabled: true,
        MessageInName: 'REPEATER',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'Status',
        Enabled: false,
        MessageInName: 'REPEATER',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Status',
      },
      {
        TypeName: 'LORA',
        InstanceName: 'sndlora1',
        MessageInSubTypeName: 'SIMessage',
        Enabled: true,
        MessageInName: 'LORA',
        MessageOutName: 'LORA',
        MessageOutSubTypeName: 'Ack',
      },
      {
        TypeName: 'BLENO',
        InstanceName: 'bleno1',
        MessageInSubTypeName: 'SIMessage',
        Enabled: false,
        MessageInName: 'SI',
        MessageOutName: 'SI',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'BLENO',
        InstanceName: 'bleno1',
        MessageInSubTypeName: 'SIMessage',
        Enabled: false,
        MessageInName: 'LORA',
        MessageOutName: 'SI',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'BLENO',
        InstanceName: 'bleno1',
        MessageInSubTypeName: 'SIMessageDouble',
        Enabled: false,
        MessageInName: 'LORA',
        MessageOutName: 'SI',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'BLENO',
        InstanceName: 'bleno1',
        MessageInSubTypeName: 'SRRMessage',
        Enabled: false,
        MessageInName: 'SRR',
        MessageOutName: 'SI',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'BLENO',
        InstanceName: 'bleno1',
        MessageInSubTypeName: 'Test',
        Enabled: false,
        MessageInName: 'SITEST',
        MessageOutName: 'SI',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'SIRAP',
        InstanceName: 'sirap1',
        MessageInSubTypeName: 'SIMessage',
        Enabled: false,
        MessageInName: 'LORA',
        MessageOutName: 'SIRAP',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'SIRAP',
        InstanceName: 'sirap1',
        MessageInSubTypeName: 'SIMessage',
        Enabled: false,
        MessageInName: 'SI',
        MessageOutName: 'SIRAP',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'SIRAP',
        InstanceName: 'sirap1',
        MessageInSubTypeName: 'Test',
        Enabled: false,
        MessageInName: 'SITEST',
        MessageOutName: 'SIRAP',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'SIRAP',
        InstanceName: 'sirap1',
        MessageInSubTypeName: 'SIMessageDouble',
        Enabled: false,
        MessageInName: 'LORA',
        MessageOutName: 'SIRAP',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'SIRAP',
        InstanceName: 'sirap1',
        MessageInSubTypeName: 'SRRMessage',
        Enabled: false,
        MessageInName: 'SRR',
        MessageOutName: 'SIRAP',
        MessageOutSubTypeName: 'Punch',
      },
      {
        TypeName: 'STATUS',
        InstanceName: 'status1',
        MessageInSubTypeName: 'Status',
        Enabled: true,
        MessageInName: 'LORA',
        MessageOutName: 'STATUS',
        MessageOutSubTypeName: 'Status',
      },
      {
        TypeName: 'STATUS',
        InstanceName: 'status1',
        MessageInSubTypeName: 'Status',
        Enabled: true,
        MessageInName: 'STATUS',
        MessageOutName: 'STATUS',
        MessageOutSubTypeName: 'Status',
      },
    ],
  }),
  settings: JSON.stringify({
    settings: [
      {
        Key: 'PowerCycle',
        Value: '41',
      },
      {
        Key: 'ReceiveSIAdapterActive',
        Value: '0',
      },
      {
        Key: 'Channel',
        Value: '2',
      },
      {
        Key: 'AcknowledgementRequested',
        Value: '1',
      },
      {
        Key: 'LoraMode',
        Value: 'RECEIVER',
      },
      {
        Key: 'LoraRange',
        Value: 'L',
      },
      {
        Key: 'SendToSirapEnabled',
        Value: '0',
      },
      {
        Key: 'SendSerialAdapterActive',
        Value: '0',
      },
      {
        Key: 'SendToSirapIPPort',
        Value: '10000',
      },
      {
        Key: 'RS232Mode',
        Value: 'RECEIVE',
      },
      {
        Key: 'SendStatusMessages',
        Value: '1',
      },
      {
        Key: 'LoraPower',
        Value: '22',
      },
      {
        Key: 'CodeRate',
        Value: '0',
      },
      {
        Key: 'RxGainEnabled',
        Value: '1',
      },
      {
        Key: 'SendToBlenoEnabled',
        Value: '0',
      },
      {
        Key: 'WebServerUrl',
        Value: 'https://monitor.wiroc.se',
      },
      {
        Key: 'LogToServer',
        Value: '0',
      },
      {
        Key: 'StatusMessageBaseInterval',
        Value: '300',
      },
      {
        Key: 'LoggingServerHost',
        Value: '',
      },
      {
        Key: 'LoggingServerPort',
        Value: '3000',
      },
      {
        Key: 'SimulatedMessageDropPercentageRepeaterNotRequested',
        Value: '0',
      },
      {
        Key: 'SettingUpdatedByWebService',
        Value: '0',
      },
      {
        Key: 'ShouldAlwaysRequestRepeater',
        Value: '0',
      },
      {
        Key: 'SRREnabled',
        Value: '1',
      },
      {
        Key: 'BTSerialOneWayReceive',
        Value: '1',
      },
      {
        Key: 'ForceRS2324800BaudRate',
        Value: '0',
      },
    ],
  }),
  'btserial/onewayreceive': '1',
  'network/ip': '192.168.1.115',
  'rtc/wakeupenabled': '0',
  'device/version/wirocbleapi': '0.14',
  'device/version/wirochw': 'v8Rev2',
  'device/version/wirocpython': '0.210',
  'rtc/datetime': '2024-01-01 10:10:00',
  'rtc/wakeup': '10:15',
  'lora/power': '22',
  'lora/coderate': '0',
  'lora/enabled': '1',
  'ham/enabled': '0',
  'ham/callsign': '',

  'lora/acknowledgementrequested': '1',
  datarate: '6',
  ipaddress: '192.168.1.115',
  'network/wifiip': '',
  'network/usbethernetip': '192.168.100.10',
  'network/ethernetip': '192.168.1.115',
  'network/interfaces': JSON.stringify(['end0', 'eth0', 'wlan0', 'usb0']),
  webserverurl: 'https://monitor.wiroc.se',
  'lora/rxgainenabled': '1',
  'btserial/force4800baudrate': '0',
  'bluetooth/rfcomm': JSON.stringify([]),
  'srr/hassendmode': '0',

  'network/wifimesh/enabled': '0',
  'network/wifimesh/gateway/enabled': '0',
  'network/wifimesh/nodenumber': '1',
  'network/wifimesh/ipnetworknumber': '0',
  'network/wifimesh/ipaddress': '',
  'network/wifimesh/interfacecreated': '0',
  'network/wifimesh/mac': '',
  'network/wifimesh/routetointerface': 'wlan0',
  'network/wifimesh/mpath': JSON.stringify({mpaths: []}),
  'network/wifimesh/restrictenabled': '0',
  'network/wifimesh/allowedips': '[]',

  'network/tailscale/enabled': '0',
  'network/tailscale/login': '',
  'network/tailscale/status': JSON.stringify({
    Version: '1.80.0',
    TUN: false,
    BackendState: 'NoState',
    TailscaleIPs: [],
    Self: {
      ID: 'demo-node',
      HostName: 'WiRocDemo',
      Online: false,
      TailscaleIPs: [],
      UserID: undefined,
    },
    Peer: {},
    User: {},
  }),
  'network/tailscale/prefs': JSON.stringify({
    RouteAll: false,
    LoggedOut: true,
    AdvertiseRoutes: null,
  }),

  'roc/enabled': '0',
};
